### ISSUE TITLE
the installation of FiRE in a more easier way

### ISSUE THREAD

**Issue by chenxofhit** [princethewinner/FiRE#3]
Today when I wanna evaluate my methods with FiRE on the Google Colab python notebook, I found it difficult to first install FiRE on that cloud-based machine. Maybe a more friendly way should be improved in the future, such as pip install.

**Comment by Nupurahluwalia** [comment]
I am facing the similar issue. Can you help me resolve this?

**Comment by chenxofhit** [comment]
@Nupurahluwalia I do not try it again, a long time has passed and I turn to another topic now.  I do not know whether the authors are still supporting this repo now. Anyway, best luck always with you.
